[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn discuso.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"

[phases.setup]
nixPkgs = ["python312", "gcc"]
aptPkgs = ["python3-dev", "python3-pip", "python3-venv"]

[phases.install]
cmds = ["python -m ensurepip --upgrade"]

[phases.build]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip setuptools wheel",
    "pip install --no-cache-dir -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[variables]
PYTHONUNBUFFERED = "1"
PATH = "/opt/venv/bin:$PATH"
