[phases.setup]
aptPkgs = [
    "python3-dev",
    "build-essential",
    "zlib1g-dev",
    "libjpeg-dev",
    "libpng-dev",
    "libtiff-dev",
    "pkg-config"
]

[phases.build]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn discuso.wsgi:application --log-file -"
