[phases.setup]
nixPkgs = [
    "python312",
    "gcc",
    "zlib",
    "libjpeg",
    "libpng",
    "libtiff",
    "pkg-config"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install wheel setuptools"
]

[phases.build]
cmds = [
    "pip install --no-cache-dir -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn discuso.wsgi:application --bind 0.0.0.0:$PORT"
